apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: loja-api-staging
patches:
- path: ingress-patch.yaml
images:
- name: ghcr.io/felipe-e-ribeiro/pos-loja-api
  newName: ghcr.io/felipe-e-ribeiro/pos-loja-api
  newTag: "8450253"
